### ISSUE TITLE
PubNub Dependency - Xamarin.Android on Windows

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp#5]
When building on Xamarin.Android for Windows, the build fails with the following error:

```
Target _ResolveAssemblies:

    C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1147,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
    C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1147,2): error : File name: 'System.Configuration.dll'
    C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1147,2): error :    at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
    C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1147,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
    C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1147,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.Execute()

Done building target "_ResolveAssemblies" in project "android006.csproj" -- FAILED.
```

**Comment by grokify** [comment]
The PubNub Xamarin.Android on Windows issue is being raised with PubNub now.
